global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Болтай и Знакомься API
  - job_name: 'boltaiznakomsya-api'
    static_configs:
      - targets: ['localhost:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
    # Метки для группировки метрик
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        regex: '(.*)'
        replacement: 'boltaiznakomsya-api'

  # Node.js приложение (если используем node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # PostgreSQL (если используем postgres_exporter)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s

  # Redis (если используем redis_exporter)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s

# Алерты
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Правила алертов
rule_files:
  - "alerts.yml" 